### PR TITLE
Add chords to title music

### PR DESCRIPTION
**Pull request by ghost**
They helped me a lot to learn and play the music fluently.

You might want to update the other formats, I don't know how your toolchain was set up.

### CODE REVIEW

**Comment by geraldhumphries** [comment]
Hey, thanks. I'm downloading TuxGuitar now to check it out.

I used GuitarPro to create the .gpx and .gp5 files, and TuxGuitar to generate the .txt files from the .gpx. Been a while, but TuxGuitar didn't add any extra symbols like harmonics to the .txt version. Chords might have the same problem which would mean adding them manually.

What software did you use? Can you try exporting to .txt? If the output is nice and includes chords, can you commit it and add it to the PR?

**Comment by geraldhumphries** [comment]
Just tried exporting to ASCII through TuxGuitar and the output is the same, no chords included. The chords look great, so if you also used TuxGuitar or your tool's ASCII output isn't any better then I can merge right away.

**Comment by ghost** [comment]
Jup, I used TuxGuitar.

Thanks for taking a look.

**Comment by geraldhumphries** [comment]
Congrats on being the first person to contribute to these tabs, ever! I released them 10 years ago and never had anyone contribute.

**Comment by ghost** [comment]
I saw :grin: 

Wait... 10? Something doesn't add up: 5b8d59b72859e792178af024ee2c1875093a9be4

**Comment by geraldhumphries** [comment]
Yeah the original release was in April 2010 on the Bay 12 forums. I
committed it to GitHub a few years later.

**Pull request merged**
